### PR TITLE
Working HMR for language json files

### PR DESCRIPTION
**Pull request by benjaminlgt-littlelives**
Working HMR for language json files

### CODE REVIEW

**Comment by mxstbr** [comment]
That's a nice solution, I like it! :+1:

**Comment by mxstbr** [comment]
A comment explaining what the code does would be nice though

**Comment by benjaminlgt-littlelives** [comment]
The code allows the hot reload event to bubble up to app.js where it is caught and processed through a re-render.

modules.hot.accept does not accept dynamic dependencies, have to be constants at compile-time.

**Comment by mxstbr** [comment]
No I mean, I understand what it's doing, I want a comment in the code :grin:

**Comment by benjaminlgt-littlelives** [comment]
Added comments :smile:

**Comment by mxstbr** [comment]
:+1:

**Pull request merged**
